sync:
  defaults:
    mode: "two-way-resolved"
    probeMode: "assume"

    symlink:
      mode: "posix-raw"

    ignore:
      paths:
        - ".DS_Store"
        - "._*"
        - "/var/cache"
        - "/var/page_cache"
        - "/.idea"
        - "/dev/tests/api-functional/tmp"
        - "/dev/tests/integration/tmp"
        - "/dev/tests/setup-integration/tmp"
        - "/dev/tests/unit/tmp"
        - "/node_modules"
      vcs: false
